<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SARANG-PC" name="com.sarangjaiswal.core.ddf.testcases.DummyTestC" tests="3" failures="2" timestamp="14 Jun 2017 14:14:29 GMT" time="3.050" errors="1">
  <testcase name="TestC" time="0.001" classname="com.sarangjaiswal.core.ddf.testcases.DummyTestC"/>
  <testcase name="TestA" time="3.037" classname="com.sarangjaiswal.core.ddf.testcases.DummyTestC">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;[A]&gt; but was:&lt;[B]&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[A]> but was:<[B]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.sarangjaiswal.core.ddf.testcases.DummyTestC.TestA(DummyTestC.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TestA -->
  <testcase name="TestB" time="0.012" classname="com.sarangjaiswal.core.ddf.testcases.DummyTestC"/>
</testsuite> <!-- com.sarangjaiswal.core.ddf.testcases.DummyTestC -->
